// Generated by stratus_hls 19.12-s100  (91710.131054)
// Thu Apr 14 13:47:03 2022
// from ../GaussianFilter.cpp

`timescale 1ps / 1ps

      
module GaussianFilter_ROM_9X32_mask(in1, out1, clk);

      input [3:0] in1;
      input clk;
      output [31:0] out1;
      reg [31:0] out1;
      reg[31:0] mask[8:0];

         initial begin
            $readmemh("bdw_work/modules/GaussianFilter/DPA/GaussianFilter_ROM_9X32_mask_0.memh", mask);
         end

         always @(posedge clk)
          begin :GaussianFilter_ROM_9X32_mask_mask_thread_1
            if (in1 < 4'd09) begin
               out1 <= mask[in1];
            end
         end


endmodule

