`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 14 2022 13:33:44 CST (Apr 14 2022 05:33:44 UTC)

module GaussianFilter_Div_10Ux2U_8U_1(in2, in1, out1);
  input [9:0] in2;
  input [1:0] in1;
  output [7:0] out1;
  wire [9:0] in2;
  wire [1:0] in1;
  wire [7:0] out1;
  wire in2_28_2_, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_24, n_25;
  wire n_28, n_29, n_30, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_67, n_68, n_69, n_70, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_81, n_82, n_84, n_89;
  wire n_95, n_97, n_128, n_139, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, sub_61_2_n_1,
       sub_61_2_n_2;
  wire sub_61_2_n_12, sub_80_2_n_0, sub_80_2_n_2, sub_80_2_n_3,
       sub_80_2_n_5, sub_80_2_n_6, sub_80_2_n_8, sub_80_2_n_16;
  wire sub_80_2_n_17, sub_99_2_n_0, sub_99_2_n_2, sub_99_2_n_5,
       sub_99_2_n_12, sub_99_2_n_16, sub_99_2_n_17, sub_120_2_n_0;
  wire sub_120_2_n_1, sub_120_2_n_3, sub_120_2_n_6, sub_120_2_n_13,
       sub_120_2_n_17, sub_120_2_n_18, sub_141_2_n_0, sub_141_2_n_2;
  wire sub_141_2_n_5, sub_141_2_n_12, sub_141_2_n_16, sub_141_2_n_17,
       sub_162_2_n_0, sub_162_2_n_1, sub_162_2_n_3, sub_162_2_n_6;
  wire sub_162_2_n_13, sub_162_2_n_17, sub_162_2_n_18, sub_183_2_n_0,
       sub_183_2_n_3, sub_183_2_n_6, sub_183_2_n_14, sub_183_2_n_17;
  wire sub_183_2_n_18, sub_204_2_n_0, sub_204_2_n_1, sub_204_2_n_2,
       sub_204_2_n_4, sub_204_2_n_7, sub_204_2_n_16, sub_204_2_n_17;
  wire sub_225_2_n_0, sub_225_2_n_1, sub_225_2_n_2, sub_225_2_n_4,
       sub_225_2_n_5, sub_225_2_n_7, sub_225_2_n_8, sub_225_2_n_10;
  wire sub_225_2_n_19, sub_225_2_n_20, sub_244_2_n_2, sub_244_2_n_3,
       sub_244_2_n_4, sub_244_2_n_5, sub_244_2_n_13;
  INVX1 g119(.A (in2_28_2_), .Y (out1[0]));
  OAI2BB1X1 g114(.A0N (in2[7]), .A1N (n_69), .B0 (n_30), .Y (n_65));
  NAND2BX1 g120(.AN (n_69), .B (n_67), .Y (n_30));
  MXI2XL g121(.A (n_28), .B (n_97), .S0 (n_89), .Y (n_61));
  NAND2X2 g115(.A (n_29), .B (n_25), .Y (n_60));
  NAND2X1 g117(.A (in2[6]), .B (n_64), .Y (n_29));
  INVX1 g118(.A (n_63), .Y (n_28));
  NAND2BX1 g123(.AN (n_64), .B (n_62), .Y (n_25));
  NAND2X2 g116(.A (n_24), .B (n_22), .Y (n_70));
  NAND2X1 g125(.A (in2[8]), .B (n_74), .Y (n_24));
  NAND2BX1 g127(.AN (n_74), .B (n_72), .Y (n_22));
  OAI2BB1X1 g129(.A0N (n_59), .A1N (n_60), .B0 (n_17), .Y (n_56));
  NAND2X2 g130(.A (n_19), .B (n_20), .Y (n_55));
  OR2X1 g131(.A (n_18), .B (n_59), .Y (n_20));
  NAND2X1 g132(.A (in2[5]), .B (n_59), .Y (n_19));
  INVX1 g133(.A (n_57), .Y (n_18));
  NAND2BX1 g134(.AN (n_59), .B (n_58), .Y (n_17));
  NAND2X2 g108(.A (n_16), .B (n_15), .Y (n_75));
  NAND2X1 g109(.A (in2[9]), .B (n_77), .Y (n_16));
  NAND2X2 g110(.A (n_14), .B (n_76), .Y (n_15));
  CLKINVX2 g111(.A (n_77), .Y (n_14));
  OAI2BB1X1 g135(.A0N (n_139), .A1N (n_55), .B0 (n_11), .Y (n_51));
  OAI2BB1X1 g136(.A0N (in2[4]), .A1N (n_54), .B0 (n_13), .Y (n_50));
  OR2XL g137(.A (n_12), .B (n_54), .Y (n_13));
  INVXL g138(.A (n_52), .Y (n_12));
  NAND2BX1 g139(.AN (n_139), .B (n_53), .Y (n_11));
  OAI2BB1X1 g140(.A0N (n_49), .A1N (n_50), .B0 (n_8), .Y (n_46));
  OAI2BB1X1 g141(.A0N (in2[3]), .A1N (n_49), .B0 (n_10), .Y (n_45));
  OR2XL g142(.A (n_9), .B (n_49), .Y (n_10));
  INVXL g143(.A (n_47), .Y (n_9));
  NAND2BX1 g144(.AN (n_49), .B (n_48), .Y (n_8));
  OAI2BB1X1 g145(.A0N (n_84), .A1N (n_45), .B0 (n_5), .Y (n_41));
  OAI2BB1X1 g146(.A0N (in2[2]), .A1N (n_44), .B0 (n_7), .Y (n_40));
  OR2XL g147(.A (n_6), .B (n_44), .Y (n_7));
  INVXL g148(.A (n_42), .Y (n_6));
  NAND2BX1 g149(.AN (n_84), .B (n_43), .Y (n_5));
  MXI2XL g150(.A (n_3), .B (n_1), .S0 (n_95), .Y (n_36));
  OAI2BB1X1 g151(.A0N (in2[1]), .A1N (n_39), .B0 (n_4), .Y (n_35));
  OR2XL g152(.A (n_2), .B (n_39), .Y (n_4));
  INVX1 g153(.A (n_38), .Y (n_3));
  INVXL g154(.A (n_37), .Y (n_2));
  INVXL g155(.A (n_40), .Y (n_1));
  INVX1 g107(.A (n_59), .Y (out1[5]));
  INVX1 g158(.A (n_49), .Y (out1[3]));
  MX2X1 g160(.A (n_68), .B (n_70), .S0 (n_128), .Y (n_81));
  MX2XL g2(.A (n_73), .B (n_75), .S0 (n_74), .Y (n_82));
  CLKINVX1 fopt161(.A (n_84), .Y (out1[2]));
  BUFX3 fopt162(.A (n_44), .Y (n_84));
  CLKINVX1 fopt164(.A (n_89), .Y (out1[6]));
  BUFX3 fopt165(.A (n_64), .Y (n_89));
  CLKINVX1 fopt(.A (n_95), .Y (out1[1]));
  BUFX3 fopt167(.A (n_39), .Y (n_95));
  INVXL fopt168(.A (n_65), .Y (n_97));
  CLKINVX1 fopt178(.A (n_128), .Y (out1[7]));
  BUFX3 fopt179(.A (n_69), .Y (n_128));
  CLKINVX1 fopt185(.A (n_139), .Y (out1[4]));
  BUFX3 fopt186(.A (n_54), .Y (n_139));
  INVXL fopt197(.A (n_165), .Y (n_163));
  INVXL fopt198(.A (n_165), .Y (n_164));
  INVXL fopt199(.A (n_166), .Y (n_165));
  BUFX3 fopt200(.A (n_167), .Y (n_166));
  BUFX3 fopt201(.A (n_168), .Y (n_167));
  BUFX3 fopt202(.A (n_169), .Y (n_168));
  BUFX3 fopt203(.A (n_170), .Y (n_169));
  BUFX3 fopt204(.A (n_171), .Y (n_170));
  BUFX3 fopt205(.A (n_172), .Y (n_171));
  BUFX3 fopt206(.A (in1[1]), .Y (n_172));
  MXI2X1 sub_120_2_g45(.A (sub_120_2_n_1), .B (n_81), .S0
       (sub_120_2_n_6), .Y (n_64));
  ACHCONX2 sub_120_2_g46(.A (sub_120_2_n_3), .B (sub_120_2_n_18), .CI
       (n_65), .CON (sub_120_2_n_6));
  XNOR3XL sub_120_2_g47(.A (sub_120_2_n_3), .B (sub_120_2_n_17), .C
       (sub_120_2_n_13), .Y (n_63));
  OAI2BB1X1 sub_120_2_g48(.A0N (in2[6]), .A1N (sub_120_2_n_0), .B0
       (sub_120_2_n_3), .Y (n_62));
  NAND2BX1 sub_120_2_g49(.AN (in2[6]), .B (in1[0]), .Y (sub_120_2_n_3));
  INVX1 sub_120_2_g51(.A (n_81), .Y (sub_120_2_n_1));
  INVX1 sub_120_2_g52(.A (in1[0]), .Y (sub_120_2_n_0));
  BUFX3 sub_120_2_fopt(.A (n_65), .Y (sub_120_2_n_13));
  CLKINVX1 sub_120_2_fopt53(.A (sub_120_2_n_18), .Y (sub_120_2_n_17));
  CLKINVX6 sub_120_2_fopt54(.A (n_170), .Y (sub_120_2_n_18));
  NAND2X2 sub_61_2_g31(.A (sub_61_2_n_2), .B (sub_61_2_n_1), .Y (n_76));
  NAND2X8 sub_61_2_g38(.A (in1[0]), .B (sub_61_2_n_12), .Y
       (sub_61_2_n_2));
  NAND2BX1 sub_61_2_g2(.AN (in1[0]), .B (in2[9]), .Y (sub_61_2_n_1));
  NAND2BX4 sub_61_2_g39(.AN (in1[1]), .B (sub_61_2_n_2), .Y (n_77));
  CLKINVX8 sub_61_2_fopt40(.A (in2[9]), .Y (sub_61_2_n_12));
  ACHCONX2 sub_183_2_g46(.A (sub_183_2_n_3), .B (sub_183_2_n_18), .CI
       (n_50), .CON (sub_183_2_n_6));
  XNOR3XL sub_183_2_g47(.A (sub_183_2_n_3), .B (sub_183_2_n_17), .C
       (sub_183_2_n_14), .Y (n_48));
  OAI2BB1X1 sub_183_2_g48(.A0N (in2[3]), .A1N (sub_183_2_n_0), .B0
       (sub_183_2_n_3), .Y (n_47));
  NAND2BX1 sub_183_2_g49(.AN (in2[3]), .B (in1[0]), .Y (sub_183_2_n_3));
  INVX1 sub_183_2_g52(.A (in1[0]), .Y (sub_183_2_n_0));
  CLKXOR2X1 sub_183_2_g2(.A (n_51), .B (sub_183_2_n_6), .Y (n_49));
  BUFX3 sub_183_2_fopt(.A (n_50), .Y (sub_183_2_n_14));
  CLKINVX1 sub_183_2_fopt53(.A (sub_183_2_n_18), .Y (sub_183_2_n_17));
  CLKINVX6 sub_183_2_fopt54(.A (n_167), .Y (sub_183_2_n_18));
  NOR2X1 sub_80_2_g40(.A (sub_80_2_n_6), .B (sub_80_2_n_8), .Y (n_74));
  NOR2BX1 sub_80_2_g42(.AN (sub_80_2_n_2), .B (sub_80_2_n_5), .Y
       (sub_80_2_n_8));
  NAND2X1 sub_80_2_g43(.A (sub_80_2_n_2), .B (sub_80_2_n_0), .Y (n_72));
  NOR2BX1 sub_80_2_g44(.AN (sub_80_2_n_17), .B (sub_80_2_n_3), .Y
       (sub_80_2_n_6));
  NOR2X1 sub_80_2_g47(.A (sub_80_2_n_16), .B (n_75), .Y (sub_80_2_n_5));
  INVX1 sub_80_2_g51(.A (n_75), .Y (sub_80_2_n_3));
  NAND2BX1 sub_80_2_g2(.AN (in2[8]), .B (in1[0]), .Y (sub_80_2_n_2));
  XOR3XL sub_80_2_g53(.A (sub_80_2_n_2), .B (n_172), .C (sub_80_2_n_3),
       .Y (n_73));
  NAND2BX1 sub_80_2_g54(.AN (in1[0]), .B (in2[8]), .Y (sub_80_2_n_0));
  CLKINVX3 sub_80_2_fopt(.A (n_172), .Y (sub_80_2_n_16));
  CLKINVX1 sub_80_2_fopt55(.A (n_172), .Y (sub_80_2_n_17));
  MXI2X1 sub_225_2_g45(.A (sub_225_2_n_2), .B (n_41), .S0
       (sub_225_2_n_10), .Y (n_39));
  NOR2X1 sub_225_2_g46(.A (sub_225_2_n_5), .B (sub_225_2_n_8), .Y
       (sub_225_2_n_10));
  XNOR3XL sub_225_2_g47(.A (sub_225_2_n_4), .B (sub_225_2_n_19), .C
       (sub_225_2_n_0), .Y (n_38));
  AOI2BB1XL sub_225_2_g48(.A0N (sub_225_2_n_20), .A1N (n_40), .B0
       (sub_225_2_n_7), .Y (sub_225_2_n_8));
  INVXL sub_225_2_g49(.A (sub_225_2_n_4), .Y (sub_225_2_n_7));
  OAI2BB1X1 sub_225_2_g50(.A0N (in2[1]), .A1N (sub_225_2_n_1), .B0
       (sub_225_2_n_4), .Y (n_37));
  AND2X1 sub_225_2_g51(.A (n_40), .B (sub_225_2_n_20), .Y
       (sub_225_2_n_5));
  NAND2BX1 sub_225_2_g52(.AN (in2[1]), .B (in1[0]), .Y (sub_225_2_n_4));
  INVX1 sub_225_2_g54(.A (n_41), .Y (sub_225_2_n_2));
  INVX1 sub_225_2_g55(.A (in1[0]), .Y (sub_225_2_n_1));
  BUFX2 sub_225_2_fopt(.A (n_40), .Y (sub_225_2_n_0));
  CLKINVX1 sub_225_2_fopt56(.A (sub_225_2_n_20), .Y (sub_225_2_n_19));
  CLKINVX1 sub_225_2_fopt57(.A (n_164), .Y (sub_225_2_n_20));
  MXI2X1 sub_162_2_g45(.A (sub_162_2_n_1), .B (n_56), .S0
       (sub_162_2_n_6), .Y (n_54));
  ACHCONX2 sub_162_2_g46(.A (sub_162_2_n_3), .B (sub_162_2_n_18), .CI
       (n_55), .CON (sub_162_2_n_6));
  XNOR3XL sub_162_2_g47(.A (sub_162_2_n_3), .B (sub_162_2_n_17), .C
       (sub_162_2_n_13), .Y (n_53));
  OAI2BB1X1 sub_162_2_g48(.A0N (in2[4]), .A1N (sub_162_2_n_0), .B0
       (sub_162_2_n_3), .Y (n_52));
  NAND2BX1 sub_162_2_g49(.AN (in2[4]), .B (in1[0]), .Y (sub_162_2_n_3));
  INVX1 sub_162_2_g51(.A (n_56), .Y (sub_162_2_n_1));
  INVX1 sub_162_2_g52(.A (in1[0]), .Y (sub_162_2_n_0));
  BUFX3 sub_162_2_fopt(.A (n_55), .Y (sub_162_2_n_13));
  CLKINVX1 sub_162_2_fopt53(.A (sub_162_2_n_18), .Y (sub_162_2_n_17));
  CLKINVX6 sub_162_2_fopt54(.A (n_168), .Y (sub_162_2_n_18));
  XOR2XL sub_244_2_g34(.A (n_36), .B (sub_244_2_n_5), .Y (in2_28_2_));
  NOR2X1 sub_244_2_g35(.A (sub_244_2_n_2), .B (sub_244_2_n_4), .Y
       (sub_244_2_n_5));
  AOI2BB1XL sub_244_2_g36(.A0N (sub_244_2_n_13), .A1N (n_35), .B0
       (sub_244_2_n_3), .Y (sub_244_2_n_4));
  NOR2BX1 sub_244_2_g37(.AN (in1[0]), .B (in2[0]), .Y (sub_244_2_n_3));
  AND2X1 sub_244_2_g38(.A (n_35), .B (sub_244_2_n_13), .Y
       (sub_244_2_n_2));
  INVXL sub_244_2_fopt(.A (n_163), .Y (sub_244_2_n_13));
  MXI2X1 sub_204_2_g45(.A (sub_204_2_n_2), .B (n_46), .S0
       (sub_204_2_n_7), .Y (n_44));
  ACHCONX2 sub_204_2_g46(.A (sub_204_2_n_4), .B (sub_204_2_n_17), .CI
       (n_45), .CON (sub_204_2_n_7));
  XNOR3XL sub_204_2_g47(.A (sub_204_2_n_4), .B (sub_204_2_n_16), .C
       (sub_204_2_n_0), .Y (n_43));
  OAI2BB1X1 sub_204_2_g48(.A0N (in2[2]), .A1N (sub_204_2_n_1), .B0
       (sub_204_2_n_4), .Y (n_42));
  NAND2BX1 sub_204_2_g49(.AN (in2[2]), .B (in1[0]), .Y (sub_204_2_n_4));
  INVX1 sub_204_2_g51(.A (n_46), .Y (sub_204_2_n_2));
  INVX1 sub_204_2_g52(.A (in1[0]), .Y (sub_204_2_n_1));
  BUFX2 sub_204_2_fopt(.A (n_45), .Y (sub_204_2_n_0));
  CLKINVX1 sub_204_2_fopt53(.A (sub_204_2_n_17), .Y (sub_204_2_n_16));
  CLKINVX6 sub_204_2_fopt54(.A (n_166), .Y (sub_204_2_n_17));
  CLKXOR2X1 sub_141_2_g45(.A (n_61), .B (sub_141_2_n_5), .Y (n_59));
  ACHCONX2 sub_141_2_g46(.A (sub_141_2_n_2), .B (sub_141_2_n_17), .CI
       (n_60), .CON (sub_141_2_n_5));
  XNOR3XL sub_141_2_g47(.A (sub_141_2_n_2), .B (sub_141_2_n_16), .C
       (sub_141_2_n_12), .Y (n_58));
  OAI2BB1X1 sub_141_2_g48(.A0N (in2[5]), .A1N (sub_141_2_n_0), .B0
       (sub_141_2_n_2), .Y (n_57));
  NAND2BX1 sub_141_2_g49(.AN (in2[5]), .B (in1[0]), .Y (sub_141_2_n_2));
  INVXL sub_141_2_g51(.A (in1[0]), .Y (sub_141_2_n_0));
  BUFX3 sub_141_2_fopt(.A (n_60), .Y (sub_141_2_n_12));
  CLKINVX1 sub_141_2_fopt52(.A (sub_141_2_n_17), .Y (sub_141_2_n_16));
  CLKINVX6 sub_141_2_fopt53(.A (n_169), .Y (sub_141_2_n_17));
  CLKXOR2X1 sub_99_2_g45(.A (n_82), .B (sub_99_2_n_5), .Y (n_69));
  ACHCONX2 sub_99_2_g46(.A (sub_99_2_n_2), .B (sub_99_2_n_17), .CI
       (n_70), .CON (sub_99_2_n_5));
  XNOR3XL sub_99_2_g47(.A (sub_99_2_n_2), .B (sub_99_2_n_16), .C
       (sub_99_2_n_12), .Y (n_68));
  OAI2BB1X1 sub_99_2_g48(.A0N (in2[7]), .A1N (sub_99_2_n_0), .B0
       (sub_99_2_n_2), .Y (n_67));
  NAND2BX1 sub_99_2_g49(.AN (in2[7]), .B (in1[0]), .Y (sub_99_2_n_2));
  INVX1 sub_99_2_g51(.A (in1[0]), .Y (sub_99_2_n_0));
  BUFX3 sub_99_2_fopt(.A (n_70), .Y (sub_99_2_n_12));
  CLKINVX1 sub_99_2_fopt52(.A (sub_99_2_n_17), .Y (sub_99_2_n_16));
  CLKINVX6 sub_99_2_fopt53(.A (n_171), .Y (sub_99_2_n_17));
endmodule


