`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 14 2022 13:42:50 CST (Apr 14 2022 05:42:50 UTC)

module GaussianFilter_Add_28Sx8U_29S_4(in2, in1, out1);
  input [27:0] in2;
  input [7:0] in1;
  output [28:0] out1;
  wire [27:0] in2;
  wire [7:0] in1;
  wire [28:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_17, add_23_2_n_19, add_23_2_n_22, add_23_2_n_23,
       add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_29;
  wire add_23_2_n_31, add_23_2_n_32, add_23_2_n_33, add_23_2_n_34,
       add_23_2_n_37, add_23_2_n_40, add_23_2_n_42, add_23_2_n_44;
  wire add_23_2_n_46, add_23_2_n_48, add_23_2_n_50, add_23_2_n_51,
       add_23_2_n_53, add_23_2_n_56, add_23_2_n_58, add_23_2_n_60;
  wire add_23_2_n_62, add_23_2_n_64, add_23_2_n_66, add_23_2_n_68,
       add_23_2_n_70, add_23_2_n_73;
  INVX1 add_23_2_g762(.A (add_23_2_n_73), .Y (out1[27]));
  ADDHX1 add_23_2_g763(.A (in2[27]), .B (add_23_2_n_70), .CO
       (out1[28]), .S (add_23_2_n_73));
  XNOR2X1 add_23_2_g764(.A (in2[26]), .B (add_23_2_n_68), .Y
       (out1[26]));
  NAND2BX1 add_23_2_g765(.AN (add_23_2_n_68), .B (in2[26]), .Y
       (add_23_2_n_70));
  XNOR2X1 add_23_2_g766(.A (in2[25]), .B (add_23_2_n_66), .Y
       (out1[25]));
  NAND2BX1 add_23_2_g767(.AN (add_23_2_n_66), .B (in2[25]), .Y
       (add_23_2_n_68));
  XNOR2X1 add_23_2_g768(.A (in2[24]), .B (add_23_2_n_64), .Y
       (out1[24]));
  NAND2BX1 add_23_2_g769(.AN (add_23_2_n_64), .B (in2[24]), .Y
       (add_23_2_n_66));
  XNOR2X1 add_23_2_g770(.A (in2[23]), .B (add_23_2_n_62), .Y
       (out1[23]));
  NAND2BX1 add_23_2_g771(.AN (add_23_2_n_62), .B (in2[23]), .Y
       (add_23_2_n_64));
  XNOR2X1 add_23_2_g772(.A (in2[22]), .B (add_23_2_n_60), .Y
       (out1[22]));
  NAND2BX1 add_23_2_g773(.AN (add_23_2_n_60), .B (in2[22]), .Y
       (add_23_2_n_62));
  XNOR2X1 add_23_2_g774(.A (in2[21]), .B (add_23_2_n_58), .Y
       (out1[21]));
  NAND2BX1 add_23_2_g775(.AN (add_23_2_n_58), .B (in2[21]), .Y
       (add_23_2_n_60));
  XNOR2X1 add_23_2_g776(.A (in2[20]), .B (add_23_2_n_56), .Y
       (out1[20]));
  NAND2BX1 add_23_2_g777(.AN (add_23_2_n_56), .B (in2[20]), .Y
       (add_23_2_n_58));
  XNOR2X1 add_23_2_g778(.A (in2[19]), .B (add_23_2_n_53), .Y
       (out1[19]));
  NAND2BX1 add_23_2_g779(.AN (add_23_2_n_53), .B (in2[19]), .Y
       (add_23_2_n_56));
  XNOR2X1 add_23_2_g780(.A (in2[17]), .B (add_23_2_n_51), .Y
       (out1[17]));
  XNOR2X1 add_23_2_g781(.A (in2[18]), .B (add_23_2_n_50), .Y
       (out1[18]));
  NAND2BX1 add_23_2_g782(.AN (add_23_2_n_50), .B (in2[18]), .Y
       (add_23_2_n_53));
  XNOR2X1 add_23_2_g783(.A (in2[16]), .B (add_23_2_n_48), .Y
       (out1[16]));
  NAND2BX1 add_23_2_g784(.AN (add_23_2_n_48), .B (in2[16]), .Y
       (add_23_2_n_51));
  NAND3BXL add_23_2_g785(.AN (add_23_2_n_48), .B (in2[17]), .C
       (in2[16]), .Y (add_23_2_n_50));
  XNOR2X1 add_23_2_g786(.A (in2[15]), .B (add_23_2_n_46), .Y
       (out1[15]));
  NAND2BX1 add_23_2_g787(.AN (add_23_2_n_46), .B (in2[15]), .Y
       (add_23_2_n_48));
  XNOR2X1 add_23_2_g788(.A (in2[14]), .B (add_23_2_n_44), .Y
       (out1[14]));
  NAND2BX1 add_23_2_g789(.AN (add_23_2_n_44), .B (in2[14]), .Y
       (add_23_2_n_46));
  XNOR2X1 add_23_2_g790(.A (in2[13]), .B (add_23_2_n_42), .Y
       (out1[13]));
  NAND2BX1 add_23_2_g791(.AN (add_23_2_n_42), .B (in2[13]), .Y
       (add_23_2_n_44));
  XNOR2X1 add_23_2_g792(.A (in2[12]), .B (add_23_2_n_40), .Y
       (out1[12]));
  NAND2BX1 add_23_2_g793(.AN (add_23_2_n_40), .B (in2[12]), .Y
       (add_23_2_n_42));
  XNOR2X1 add_23_2_g794(.A (in2[11]), .B (add_23_2_n_37), .Y
       (out1[11]));
  NAND2BX1 add_23_2_g795(.AN (add_23_2_n_37), .B (in2[11]), .Y
       (add_23_2_n_40));
  XNOR2X1 add_23_2_g796(.A (in2[9]), .B (add_23_2_n_34), .Y (out1[9]));
  XNOR2X1 add_23_2_g797(.A (in2[10]), .B (add_23_2_n_33), .Y
       (out1[10]));
  NAND2BX1 add_23_2_g798(.AN (add_23_2_n_33), .B (in2[10]), .Y
       (add_23_2_n_37));
  XNOR2X1 add_23_2_g799(.A (in2[8]), .B (add_23_2_n_31), .Y (out1[8]));
  XNOR2X1 add_23_2_g800(.A (add_23_2_n_13), .B (add_23_2_n_32), .Y
       (out1[7]));
  NAND2BX1 add_23_2_g801(.AN (add_23_2_n_31), .B (in2[8]), .Y
       (add_23_2_n_34));
  NAND3BXL add_23_2_g802(.AN (add_23_2_n_31), .B (in2[9]), .C (in2[8]),
       .Y (add_23_2_n_33));
  OAI21X1 add_23_2_g803(.A0 (add_23_2_n_4), .A1 (add_23_2_n_27), .B0
       (add_23_2_n_6), .Y (add_23_2_n_32));
  AOI211XL add_23_2_g804(.A0 (add_23_2_n_12), .A1 (add_23_2_n_14), .B0
       (add_23_2_n_29), .C0 (add_23_2_n_9), .Y (add_23_2_n_31));
  XNOR2X1 add_23_2_g805(.A (add_23_2_n_11), .B (add_23_2_n_27), .Y
       (out1[6]));
  OAI2BB1X1 add_23_2_g806(.A0N (add_23_2_n_12), .A1N (add_23_2_n_26),
       .B0 (add_23_2_n_0), .Y (add_23_2_n_29));
  XNOR2X1 add_23_2_g807(.A (add_23_2_n_10), .B (add_23_2_n_25), .Y
       (out1[5]));
  NOR2X1 add_23_2_g808(.A (add_23_2_n_14), .B (add_23_2_n_26), .Y
       (add_23_2_n_27));
  NOR2X1 add_23_2_g809(.A (add_23_2_n_1), .B (add_23_2_n_23), .Y
       (add_23_2_n_26));
  NAND2X1 add_23_2_g810(.A (add_23_2_n_2), .B (add_23_2_n_23), .Y
       (add_23_2_n_25));
  XNOR2X1 add_23_2_g811(.A (add_23_2_n_8), .B (add_23_2_n_22), .Y
       (out1[4]));
  NAND2BX1 add_23_2_g812(.AN (add_23_2_n_5), .B (add_23_2_n_22), .Y
       (add_23_2_n_23));
  ADDFX1 add_23_2_g813(.A (add_23_2_n_19), .B (in1[3]), .CI (in2[3]),
       .CO (add_23_2_n_22), .S (out1[3]));
  ADDFX1 add_23_2_g814(.A (add_23_2_n_17), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_19), .S (out1[2]));
  ADDFX1 add_23_2_g815(.A (add_23_2_n_15), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_17), .S (out1[1]));
  ADDHX1 add_23_2_g816(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_15),
       .S (out1[0]));
  OAI21X1 add_23_2_g817(.A0 (add_23_2_n_2), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_3), .Y (add_23_2_n_14));
  NAND2BX1 add_23_2_g818(.AN (add_23_2_n_7), .B (add_23_2_n_0), .Y
       (add_23_2_n_13));
  NOR2X1 add_23_2_g819(.A (add_23_2_n_7), .B (add_23_2_n_4), .Y
       (add_23_2_n_12));
  NOR2BX1 add_23_2_g820(.AN (add_23_2_n_6), .B (add_23_2_n_4), .Y
       (add_23_2_n_11));
  NAND2BX1 add_23_2_g821(.AN (add_23_2_n_1), .B (add_23_2_n_3), .Y
       (add_23_2_n_10));
  NOR2X1 add_23_2_g822(.A (add_23_2_n_6), .B (add_23_2_n_7), .Y
       (add_23_2_n_9));
  NAND2BX1 add_23_2_g823(.AN (add_23_2_n_5), .B (add_23_2_n_2), .Y
       (add_23_2_n_8));
  NOR2X1 add_23_2_g824(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g825(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_6));
  NOR2X1 add_23_2_g826(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g827(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g828(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g829(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g830(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g831(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_0));
endmodule


