`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 14 2022 13:33:22 CST (Apr 14 2022 05:33:22 UTC)

module GaussianFilter_And_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  AND2XL g8(.A (in2), .B (in1), .Y (out1));
endmodule


