// Generated by stratus_hls 19.12-s100  (91710.131054)
// Thu Apr 14 13:43:31 2022
// from ../GaussianFilter.cpp
#include "GaussianFilter_rtl.h"

struct GaussianFilter;
GaussianFilter::GaussianFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_result_busy("o_result_busy")
    ,o_result_vld("o_result_vld")
    ,o_result_data("o_result_data")
    ,o_result_m_req_m_prev_trig_req("o_result_m_req_m_prev_trig_req")
    ,GaussianFilter_Xor_1Ux1U_1U_1_1_out1("GaussianFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_result_m_unacked_req("o_result_m_unacked_req")
    ,GaussianFilter_Or_1Ux1U_1U_4_2_out1("GaussianFilter_Or_1Ux1U_1U_4_2_out1")
    ,GaussianFilter_N_Muxb_1_2_0_4_4_out1("GaussianFilter_N_Muxb_1_2_0_4_4_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,GaussianFilter_gen_busy_r_4_22_gen_busy_i_rgb_m_data_is_invalid_next("GaussianFilter_gen_busy_r_4_22_gen_busy_i_rgb_m_data_is_invalid_next")
    ,GaussianFilter_gen_busy_r_4_22_gdiv("GaussianFilter_gen_busy_r_4_22_gdiv")
    ,GaussianFilter_gen_busy_r_4_22_gnew_req("GaussianFilter_gen_busy_r_4_22_gnew_req")
    ,global_state_next("global_state_next")
    ,GaussianFilter_Add_28Sx1U_29S_4_19_in2("GaussianFilter_Add_28Sx1U_29S_4_19_in2")
    ,GaussianFilter_And_1Ux1U_1U_4_17_out1("GaussianFilter_And_1Ux1U_1U_4_17_out1")
    ,GaussianFilter_And_1Ux1U_1U_4_17_in1("GaussianFilter_And_1Ux1U_1U_4_17_in1")
    ,GaussianFilter_Div_10Ux2U_8U_4_12_out1("GaussianFilter_Div_10Ux2U_8U_4_12_out1")
    ,GaussianFilter_Add_9Ux8U_10U_4_11_out1("GaussianFilter_Add_9Ux8U_10U_4_11_out1")
    ,GaussianFilter_Add_9Ux8U_10U_4_11_in1("GaussianFilter_Add_9Ux8U_10U_4_11_in1")
    ,GaussianFilter_Add_8Ux8U_9U_4_10_in1("GaussianFilter_Add_8Ux8U_9U_4_10_in1")
    ,GaussianFilter_Add_2Ux1U_2U_4_9_in2("GaussianFilter_Add_2Ux1U_2U_4_9_in2")
    ,GaussianFilter_Add_4Ux2U_4U_4_8_in1("GaussianFilter_Add_4Ux2U_4U_4_8_in1")
    ,GaussianFilter_Mul_2Ux2U_4U_4_7_out1("GaussianFilter_Mul_2Ux2U_4U_4_7_out1")
    ,GaussianFilter_Mul_2Ux2U_4U_4_7_in2("GaussianFilter_Mul_2Ux2U_4U_4_7_in2")
    ,GaussianFilter_Add_2Ux1U_2U_4_6_in2("GaussianFilter_Add_2Ux1U_2U_4_6_in2")
    ,gs_ctrl0("gs_ctrl0")
    ,GaussianFilter_OrReduction_4U_1U_4_15_out1("GaussianFilter_OrReduction_4U_1U_4_15_out1")
    ,s_reg_19("s_reg_19")
    ,GaussianFilter_Mul_32Sx8U_32S_4_13_out1("GaussianFilter_Mul_32Sx8U_32S_4_13_out1")
    ,s_reg_18("s_reg_18")
    ,GaussianFilter_Add_2Ux1U_2U_4_9_out1("GaussianFilter_Add_2Ux1U_2U_4_9_out1")
    ,s_reg_17("s_reg_17")
    ,GaussianFilter_Add_8Ux8U_9U_4_10_out1("GaussianFilter_Add_8Ux8U_9U_4_10_out1")
    ,GaussianFilter_Add_4Ux2U_4U_4_8_out1("GaussianFilter_Add_4Ux2U_4U_4_8_out1")
    ,s_reg_16("s_reg_16")
    ,GaussianFilter_Add_2Ux1U_2U_4_6_out1("GaussianFilter_Add_2Ux1U_2U_4_6_out1")
    ,s_reg_15("s_reg_15")
    ,s_reg_14("s_reg_14")
    ,GaussianFilter_gen_busy_r_4_22_out1("GaussianFilter_gen_busy_r_4_22_out1")
    ,GaussianFilter_And_1Ux1U_1U_4_20_out1("GaussianFilter_And_1Ux1U_1U_4_20_out1")
    ,GaussianFilter_Not_1U_1U_1_3_out1("GaussianFilter_Not_1U_1U_1_3_out1")
    ,o_result_m_req_m_trig_req("o_result_m_req_m_trig_req")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,GaussianFilter_Add_28Sx1U_29S_4_19_out1("GaussianFilter_Add_28Sx1U_29S_4_19_out1")
    ,GaussianFilter_LessThan_2Ux2U_1U_4_18_out1("GaussianFilter_LessThan_2Ux2U_1U_4_18_out1")
    ,GaussianFilter_LessThan_2Ux2U_1U_4_16_out1("GaussianFilter_LessThan_2Ux2U_1U_4_16_out1")
    ,GaussianFilter_Add_32Ux32U_32U_4_14_out1("GaussianFilter_Add_32Ux32U_32U_4_14_out1")
    ,global_state("global_state")
    ,stall0("stall0")
    ,mask_in1("mask_in1")
    ,mask_out1("mask_out1")
{
  mask = new GaussianFilter_ROM_9X32_mask("mask");
  mask->in1(mask_in1);
  mask->out1(mask_out1);
  mask->clk(i_clk);

  SC_METHOD(drive_o_result_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( GaussianFilter_gen_busy_r_4_22_out1 );
  sensitive << ( GaussianFilter_And_1Ux1U_1U_4_20_out1 );

  SC_METHOD(drive_s_reg_14);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_15);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_16);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_17);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_18);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_19);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_GaussianFilter_Add_2Ux1U_2U_4_6_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_15 );

  SC_METHOD(GaussianFilter_Add_2Ux1U_2U_4_6);
  sensitive << ( GaussianFilter_Add_2Ux1U_2U_4_6_in2 );

  SC_METHOD(drive_GaussianFilter_Mul_2Ux2U_4U_4_7_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1 );
  sensitive << ( s_reg_17 );

  SC_METHOD(GaussianFilter_Mul_2Ux2U_4U_4_7);
  sensitive << ( GaussianFilter_Mul_2Ux2U_4U_4_7_in2 );

  SC_METHOD(drive_GaussianFilter_Add_4Ux2U_4U_4_8_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1 );
  sensitive << ( s_reg_14 );
  sensitive << ( s_reg_15 );

  SC_METHOD(GaussianFilter_Add_4Ux2U_4U_4_8);
  sensitive << ( GaussianFilter_Add_4Ux2U_4U_4_8_in1 );
  sensitive << ( GaussianFilter_Mul_2Ux2U_4U_4_7_out1 );

  SC_METHOD(drive_GaussianFilter_Add_2Ux1U_2U_4_9_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1 );
  sensitive << ( s_reg_17 );

  SC_METHOD(GaussianFilter_Add_2Ux1U_2U_4_9);
  sensitive << ( GaussianFilter_Add_2Ux1U_2U_4_9_in2 );

  SC_METHOD(drive_GaussianFilter_Add_8Ux8U_9U_4_10_in1);
  sensitive << ( i_rgb_data );

  SC_METHOD(GaussianFilter_Add_8Ux8U_9U_4_10);
  sensitive << ( GaussianFilter_Add_8Ux8U_9U_4_10_in1 );
  sensitive << ( i_rgb_data );

  SC_METHOD(drive_GaussianFilter_Add_9Ux8U_10U_4_11_in1);
  sensitive << ( s_reg_18 );

  SC_METHOD(GaussianFilter_Add_9Ux8U_10U_4_11);
  sensitive << ( GaussianFilter_Add_9Ux8U_10U_4_11_in1 );
  sensitive << ( s_reg_16 );

  SC_METHOD(drive_mask_in1);
  sensitive << ( s_reg_16 );

  SC_METHOD(GaussianFilter_Div_10Ux2U_8U_4_12);
  sensitive << ( GaussianFilter_Add_9Ux8U_10U_4_11_out1 );

  SC_METHOD(GaussianFilter_Mul_32Sx8U_32S_4_13);
  sensitive << ( GaussianFilter_Div_10Ux2U_8U_4_12_out1 );
  sensitive << ( mask_out1 );

  SC_METHOD(GaussianFilter_Add_32Ux32U_32U_4_14);
  sensitive << ( o_result_data );
  sensitive << ( s_reg_18 );

  SC_METHOD(GaussianFilter_OrReduction_4U_1U_4_15);
  sensitive << ( GaussianFilter_Add_32Ux32U_32U_4_14_out1 );

  SC_METHOD(GaussianFilter_LessThan_2Ux2U_1U_4_16);
  sensitive << ( s_reg_17 );

  SC_METHOD(drive_GaussianFilter_And_1Ux1U_1U_4_17_in1);
  sensitive << ( o_result_data );

  SC_METHOD(GaussianFilter_And_1Ux1U_1U_4_17);
  sensitive << ( GaussianFilter_And_1Ux1U_1U_4_17_in1 );
  sensitive << ( s_reg_19 );

  SC_METHOD(GaussianFilter_LessThan_2Ux2U_1U_4_18);
  sensitive << ( s_reg_15 );

  SC_METHOD(drive_GaussianFilter_Add_28Sx1U_29S_4_19_in2);
  sensitive << ( o_result_data );

  SC_METHOD(GaussianFilter_Add_28Sx1U_29S_4_19);
  sensitive << ( GaussianFilter_And_1Ux1U_1U_4_17_out1 );
  sensitive << ( GaussianFilter_Add_28Sx1U_29S_4_19_in2 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1 );
  sensitive << ( GaussianFilter_LessThan_2Ux2U_1U_4_18_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( GaussianFilter_gen_busy_r_4_22_out1 );

  SC_METHOD(GaussianFilter_gen_busy_r_4_22_p8);
  sensitive << ( 
  GaussianFilter_gen_busy_r_4_22_gen_busy_i_rgb_m_data_is_invalid_next );
  sensitive << ( GaussianFilter_gen_busy_r_4_22_gdiv );
  sensitive << ( GaussianFilter_gen_busy_r_4_22_gnew_req );

  SC_METHOD(GaussianFilter_gen_busy_r_4_22_p7);
  sensitive << ( GaussianFilter_gen_busy_r_4_22_gdiv );

  SC_METHOD(GaussianFilter_gen_busy_r_4_22_p6);
  sensitive << ( GaussianFilter_gen_busy_r_4_22_gnew_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(GaussianFilter_gen_busy_r_4_22_p5);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_m_busy_req_0 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussianFilter_N_Muxb_1_2_0_4_4);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_o_result_vld);
  sensitive << ( GaussianFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(GaussianFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( GaussianFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_result_m_unacked_req );

  SC_METHOD(drive_o_result_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussianFilter_And_1Ux1U_1U_4_20);
  sensitive << ( o_result_vld );
  sensitive << ( o_result_busy );

  SC_METHOD(GaussianFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_result_m_req_m_prev_trig_req );
  sensitive << ( o_result_m_req_m_trig_req );

  SC_METHOD(drive_o_result_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(GaussianFilter_Not_1U_1U_1_3);
  sensitive << ( o_result_m_req_m_trig_req );

}
// resource: mux_32bx3i1c
// resource: regr_en_32
void GaussianFilter::drive_o_result_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      o_result_data = 0ULL;
      break;
    case 3ULL: 
      o_result_data = (sc_uint<32> ) (GaussianFilter_Add_32Ux32U_32U_4_14_out1
                      .read());
      break;
    case 4ULL: 
      if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() );
      else {
        if ( GaussianFilter_LessThan_2Ux2U_1U_4_18_out1.read() );
        else {
          o_result_data = (sc_uint<32> ) (
                          GaussianFilter_Add_28Sx1U_29S_4_19_out1.read());
        }
      }
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void GaussianFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 0ULL: case 6ULL: 
        i_rgb_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 4ULL: 
        if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() ) {
          i_rgb_m_busy_req_0 = 0ULL;
        } else {
          if ( GaussianFilter_LessThan_2Ux2U_1U_4_18_out1.read() ) {
            i_rgb_m_busy_req_0 = 0ULL;
          } 
        }
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void GaussianFilter::drive_o_result_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state.read()) ) {
      case 4ULL: 
        if ( (!GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() && !
             GaussianFilter_LessThan_2Ux2U_1U_4_18_out1.read()) ) {
          o_result_m_req_m_trig_req = (sc_uint<1> ) (
                                      GaussianFilter_Not_1U_1U_1_3_out1.read());
        } 
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx3i1c
void GaussianFilter::drive_stall0(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = (sc_uint<1> )GaussianFilter_gen_busy_r_4_22_out1.read();
    break;
  case 5ULL: 
    stall0 = GaussianFilter_And_1Ux1U_1U_4_20_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void GaussianFilter::drive_s_reg_14(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_14 = 0ULL;
      break;
    case 4ULL: 
      if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() );
      else {
        s_reg_14 = s_reg_15.read();
      }
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GaussianFilter::drive_s_reg_15(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 6ULL: 
      s_reg_15 = (sc_uint<2> ) (GaussianFilter_Add_2Ux1U_2U_4_6_out1.read());
      break;
    case 4ULL: 
      if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() );
      else {
        s_reg_15 = (sc_uint<2> ) (GaussianFilter_Add_2Ux1U_2U_4_6_out1.read());
      }
      break;
    }
    break;
  }
}
// resource: mux_9bx2i0c
// resource: regr_en_9
void GaussianFilter::drive_s_reg_16(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 4ULL: case 6ULL: 
      s_reg_16 = (sc_uint<9> ) (GaussianFilter_Add_4Ux2U_4U_4_8_out1.read());
      break;
    case 1ULL: 
      s_reg_16 = GaussianFilter_Add_8Ux8U_9U_4_10_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_2
void GaussianFilter::drive_s_reg_17(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 0ULL: case 4ULL: case 6ULL: 
      s_reg_17 = (sc_uint<2> ) (GaussianFilter_Add_2Ux1U_2U_4_9_out1.read());
      break;
    }
    break;
  }
}
// resource: mux_32bx2i0c
// resource: regr_en_32
void GaussianFilter::drive_s_reg_18(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<3>)(global_state.read()) ) {
    case 1ULL: 
      s_reg_18 = (sc_uint<32> ) (i_rgb_data.read());
      break;
    case 2ULL: 
      s_reg_18 = (sc_uint<32> ) (GaussianFilter_Mul_32Sx8U_32S_4_13_out1.read())
      ;
      break;
    }
    break;
  }
}
// resource: regr_en_1
void GaussianFilter::drive_s_reg_19(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    s_reg_19 = GaussianFilter_OrReduction_4U_1U_4_15_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
void GaussianFilter::drive_GaussianFilter_Add_2Ux1U_2U_4_6_in2(){
  if ( gs_ctrl0.read() ) {
    GaussianFilter_Add_2Ux1U_2U_4_6_in2 = (sc_uint<2> ) (s_reg_15.read());
  } else {
    GaussianFilter_Add_2Ux1U_2U_4_6_in2 = 0ULL;
  }
}
// resource: GaussianFilter_Add_2Ux1U_2U_4  instance: GaussianFilter_Add_2Ux1U_2U_4_6
void GaussianFilter::GaussianFilter_Add_2Ux1U_2U_4_6(){
  GaussianFilter_Add_2Ux1U_2U_4_6_out1 = (/*cliff*/sc_uint<32>)(
                                         GaussianFilter_Add_2Ux1U_2U_4_6_in2
                                         .read() + 1ULL);
}
// resource: mux_2bx2i1c
void GaussianFilter::drive_GaussianFilter_Mul_2Ux2U_4U_4_7_in2(){
  if ( gs_ctrl0.read() ) {
    if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() ) {
      GaussianFilter_Mul_2Ux2U_4U_4_7_in2 = s_reg_17.read();
    } else {
      GaussianFilter_Mul_2Ux2U_4U_4_7_in2 = 0ULL;
    }
  } else {
    GaussianFilter_Mul_2Ux2U_4U_4_7_in2 = 0ULL;
  }
}
// resource: GaussianFilter_Mul_2Ux2U_4U_4  instance: GaussianFilter_Mul_2Ux2U_4U_4_7
void GaussianFilter::GaussianFilter_Mul_2Ux2U_4U_4_7(){
  GaussianFilter_Mul_2Ux2U_4U_4_7_out1 = GaussianFilter_Mul_2Ux2U_4U_4_7_in2
                                         .read() * 3ULL;
}
// resource: mux_2bx3i1c
void GaussianFilter::drive_GaussianFilter_Add_4Ux2U_4U_4_8_in1(){
  if ( gs_ctrl0.read() ) {
    if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() ) {
      GaussianFilter_Add_4Ux2U_4U_4_8_in1 = s_reg_14.read();
    } else {
      GaussianFilter_Add_4Ux2U_4U_4_8_in1 = s_reg_15.read();
    }
  } else {
    GaussianFilter_Add_4Ux2U_4U_4_8_in1 = 0ULL;
  }
}
// resource: GaussianFilter_Add_4Ux2U_4U_4  instance: GaussianFilter_Add_4Ux2U_4U_4_8
void GaussianFilter::GaussianFilter_Add_4Ux2U_4U_4_8(){
  GaussianFilter_Add_4Ux2U_4U_4_8_out1 = (GaussianFilter_Mul_2Ux2U_4U_4_7_out1
                                         .read() + 
                                         GaussianFilter_Add_4Ux2U_4U_4_8_in1
                                         .read());
}
// resource: mux_2bx2i1c
void GaussianFilter::drive_GaussianFilter_Add_2Ux1U_2U_4_9_in2(){
  if ( gs_ctrl0.read() ) {
    if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() ) {
      GaussianFilter_Add_2Ux1U_2U_4_9_in2 = (sc_uint<2> ) (s_reg_17.read());
    } else {
      GaussianFilter_Add_2Ux1U_2U_4_9_in2 = 0ULL;
    }
  } else {
    GaussianFilter_Add_2Ux1U_2U_4_9_in2 = 0ULL;
  }
}
// resource: GaussianFilter_Add_2Ux1U_2U_4  instance: GaussianFilter_Add_2Ux1U_2U_4_9
void GaussianFilter::GaussianFilter_Add_2Ux1U_2U_4_9(){
  GaussianFilter_Add_2Ux1U_2U_4_9_out1 = (/*cliff*/sc_uint<32>)(
                                         GaussianFilter_Add_2Ux1U_2U_4_9_in2
                                         .read() + 1ULL);
}
void GaussianFilter::drive_GaussianFilter_Add_8Ux8U_9U_4_10_in1(){
  GaussianFilter_Add_8Ux8U_9U_4_10_in1 = (sc_uint<8> ) (i_rgb_data.read().range(
                                         15,8));
}
// resource: GaussianFilter_Add_8Ux8U_9U_4  instance: GaussianFilter_Add_8Ux8U_9U_4_10
void GaussianFilter::GaussianFilter_Add_8Ux8U_9U_4_10(){
  GaussianFilter_Add_8Ux8U_9U_4_10_out1 = ((sc_uint<8> )i_rgb_data.read() + 
                                          GaussianFilter_Add_8Ux8U_9U_4_10_in1
                                          .read());
}
void GaussianFilter::drive_GaussianFilter_Add_9Ux8U_10U_4_11_in1(){
  GaussianFilter_Add_9Ux8U_10U_4_11_in1 = (sc_uint<8> ) (s_reg_18.read().range(
                                          23,16));
}
// resource: GaussianFilter_Add_9Ux8U_10U_4  instance: GaussianFilter_Add_9Ux8U_10U_4_11
void GaussianFilter::GaussianFilter_Add_9Ux8U_10U_4_11(){
  GaussianFilter_Add_9Ux8U_10U_4_11_out1 = (s_reg_16.read() + 
                                           GaussianFilter_Add_9Ux8U_10U_4_11_in1
                                           .read());
}
void GaussianFilter::drive_mask_in1(){
  mask_in1 = (sc_uint<4> )s_reg_16.read();
}
// resource: GaussianFilter_Div_10Ux2U_8U_4  instance: GaussianFilter_Div_10Ux2U_8U_4_12
void GaussianFilter::GaussianFilter_Div_10Ux2U_8U_4_12(){
  GaussianFilter_Div_10Ux2U_8U_4_12_out1 = ((sc_uint<2> )3ULL == 0 ? ((
                                           sc_uint<8> ) -1) : (sc_uint<8> ) (GaussianFilter_Add_9Ux8U_10U_4_11_out1
                                           .read() / (sc_uint<2> )3ULL));
}
// resource: GaussianFilter_Mul_32Sx8U_32S_4  instance: GaussianFilter_Mul_32Sx8U_32S_4_13
void GaussianFilter::GaussianFilter_Mul_32Sx8U_32S_4_13(){
  GaussianFilter_Mul_32Sx8U_32S_4_13_out1 = (/*cliff*/sc_int<32>)(sc_int<32> )
                                            mask_out1.read() * (sc_uint<8> )GaussianFilter_Div_10Ux2U_8U_4_12_out1
                                            .read();
}
// resource: GaussianFilter_Add_32Ux32U_32U_4  instance: GaussianFilter_Add_32Ux32U_32U_4_14
void GaussianFilter::GaussianFilter_Add_32Ux32U_32U_4_14(){
  GaussianFilter_Add_32Ux32U_32U_4_14_out1 = (/*cliff*/sc_uint<32>)((
                                             sc_uint<32> )s_reg_18.read() + (
                                             sc_uint<32> )o_result_data.read());
}
// resource: GaussianFilter_OrReduction_4U_1U_4  instance: GaussianFilter_OrReduction_4U_1U_4_15
void GaussianFilter::GaussianFilter_OrReduction_4U_1U_4_15(){
  GaussianFilter_OrReduction_4U_1U_4_15_out1 = ((sc_uint<4>)( (sc_uint<4> )GaussianFilter_Add_32Ux32U_32U_4_14_out1
                                               .read() )).or_reduce();
}
// resource: GaussianFilter_LessThan_2Ux2U_1U_4  instance: GaussianFilter_LessThan_2Ux2U_1U_4_16
void GaussianFilter::GaussianFilter_LessThan_2Ux2U_1U_4_16(){
  GaussianFilter_LessThan_2Ux2U_1U_4_16_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                               s_reg_17.read() < (sc_uint<2> )
                                               3ULL);
}
void GaussianFilter::drive_GaussianFilter_And_1Ux1U_1U_4_17_in1(){
  GaussianFilter_And_1Ux1U_1U_4_17_in1 = (sc_uint<1> ) (o_result_data.read()
                                         .range(31,31));
}
// resource: GaussianFilter_And_1Ux1U_1U_4  instance: GaussianFilter_And_1Ux1U_1U_4_17
void GaussianFilter::GaussianFilter_And_1Ux1U_1U_4_17(){
  GaussianFilter_And_1Ux1U_1U_4_17_out1 = s_reg_19.read() & 
                                          GaussianFilter_And_1Ux1U_1U_4_17_in1
                                          .read();
}
// resource: GaussianFilter_LessThan_2Ux2U_1U_4  instance: GaussianFilter_LessThan_2Ux2U_1U_4_18
void GaussianFilter::GaussianFilter_LessThan_2Ux2U_1U_4_18(){
  GaussianFilter_LessThan_2Ux2U_1U_4_18_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                               s_reg_15.read() < (sc_uint<2> )
                                               3ULL);
}
void GaussianFilter::drive_GaussianFilter_Add_28Sx1U_29S_4_19_in2(){
  GaussianFilter_Add_28Sx1U_29S_4_19_in2 = (sc_int<28> ) (((/*imp*/sc_uint<28> 
                                           ) o_result_data.read().range(31,4)));
}
// resource: GaussianFilter_Add_28Sx1U_29S_4  instance: GaussianFilter_Add_28Sx1U_29S_4_19
void GaussianFilter::GaussianFilter_Add_28Sx1U_29S_4_19(){
  GaussianFilter_Add_28Sx1U_29S_4_19_out1 = (/*cliff*/sc_int<32>)(GaussianFilter_Add_28Sx1U_29S_4_19_in2
                                            .read() + GaussianFilter_And_1Ux1U_1U_4_17_out1
                                            .read());
}
// resource: regr_en_sc_3
void GaussianFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_3bx2i1c
void GaussianFilter::drive_global_state_next(){
  switch( (sc_uint<3>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 6ULL: 
    global_state_next = 1ULL;
    break;
  case 4ULL: 
    if ( GaussianFilter_LessThan_2Ux2U_1U_4_16_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( GaussianFilter_LessThan_2Ux2U_1U_4_18_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void GaussianFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<3>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 4ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
      break;
    }
  }
}
void GaussianFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
               GaussianFilter_gen_busy_r_4_22_out1.read().range(2,2)));
}
// resource: GaussianFilter_gen_busy_r_4  instance: GaussianFilter_gen_busy_r_4_22
void GaussianFilter::GaussianFilter_gen_busy_r_4_22_p8(){
  GaussianFilter_gen_busy_r_4_22_out1 = (sc_uint<3> ) (( (sc_biguint<3> )
                                        (sc_bv<3>)((sc_bv<1>)(
                                        GaussianFilter_gen_busy_r_4_22_gnew_req
                                        .read()), 
                                        (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                        (sc_bv<1>)(
                                        GaussianFilter_gen_busy_r_4_22_gdiv
                                        .read()), 
                                        (sc_bv<1>)(GaussianFilter_gen_busy_r_4_22_gen_busy_i_rgb_m_data_is_invalid_next
                                        .read())) ))) ));
}
// resource: GaussianFilter_gen_busy_r_4  instance: GaussianFilter_gen_busy_r_4_22
void GaussianFilter::GaussianFilter_gen_busy_r_4_22_p7(){
  GaussianFilter_gen_busy_r_4_22_gen_busy_i_rgb_m_data_is_invalid_next = ~(sc_uint<1>)GaussianFilter_gen_busy_r_4_22_gdiv
                                                                         .read()
  ;
}
// resource: GaussianFilter_gen_busy_r_4  instance: GaussianFilter_gen_busy_r_4_22
void GaussianFilter::GaussianFilter_gen_busy_r_4_22_p6(){
  GaussianFilter_gen_busy_r_4_22_gdiv = (sc_uint<1> ) (i_rgb_vld.read() & !
                                        GaussianFilter_gen_busy_r_4_22_gnew_req
                                        .read());
}
// resource: GaussianFilter_gen_busy_r_4  instance: GaussianFilter_gen_busy_r_4_22
void GaussianFilter::GaussianFilter_gen_busy_r_4_22_p5(){
  GaussianFilter_gen_busy_r_4_22_gnew_req = (sc_uint<1> ) (i_rgb_m_busy_req_0
                                            .read() & ( i_rgb_m_unvalidated_req
                                            .read() | (sc_uint<1> )i_rgb_vld
                                            .read() ));
}
// resource: regr_ss_1
void GaussianFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (
                              GaussianFilter_N_Muxb_1_2_0_4_4_out1.read());
  }
}
// resource: GaussianFilter_N_Muxb_1_2_0_4
void GaussianFilter::GaussianFilter_N_Muxb_1_2_0_4_4(){
  if ( i_rgb_m_busy_req_0.read() ) {
    GaussianFilter_N_Muxb_1_2_0_4_4_out1 = (sc_uint<1> ) (
                                           i_rgb_m_unvalidated_req.read());
  } else {
    GaussianFilter_N_Muxb_1_2_0_4_4_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
void GaussianFilter::drive_o_result_vld(){
  o_result_vld = (sc_uint<1> ) (GaussianFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: GaussianFilter_Or_1Ux1U_1U_4  instance: GaussianFilter_Or_1Ux1U_1U_4_2
void GaussianFilter::GaussianFilter_Or_1Ux1U_1U_4_2(){
  GaussianFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_result_m_unacked_req
                                        .read() | (sc_uint<1>)
                                        GaussianFilter_Xor_1Ux1U_1U_1_1_out1
                                        .read());
}
// resource: regr_sc_1
void GaussianFilter::drive_o_result_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_unacked_req = 0ULL;
  } else {
    o_result_m_unacked_req = (sc_uint<1> ) (
                             GaussianFilter_And_1Ux1U_1U_4_20_out1.read());
  }
}
// resource: GaussianFilter_And_1Ux1U_1U_4  instance: GaussianFilter_And_1Ux1U_1U_4_20
void GaussianFilter::GaussianFilter_And_1Ux1U_1U_4_20(){
  GaussianFilter_And_1Ux1U_1U_4_20_out1 = o_result_busy.read() & o_result_vld
                                          .read();
}
// resource: GaussianFilter_Xor_1Ux1U_1U_1  instance: GaussianFilter_Xor_1Ux1U_1U_1_1
void GaussianFilter::GaussianFilter_Xor_1Ux1U_1U_1_1(){
  GaussianFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (
                                         o_result_m_req_m_trig_req.read() ^ 
                                         o_result_m_req_m_prev_trig_req.read());
}
// resource: regr_sc_1
void GaussianFilter::drive_o_result_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_m_req_m_prev_trig_req = o_result_m_req_m_trig_req.read();
  }
}
// resource: GaussianFilter_Not_1U_1U_1  instance: GaussianFilter_Not_1U_1U_1_3
void GaussianFilter::GaussianFilter_Not_1U_1U_1_3(){
  GaussianFilter_Not_1U_1U_1_3_out1 = !o_result_m_req_m_trig_req.read();
}
